bloodline/urls.py
"""urls.py

This module mostly handle the routing of the application

Variables:
	LOGIN_URL {str} -- provide default login route name
	LOGOUT_URL {str} -- provide default logout route name
	LOGIN_REDIRECT_URL {str} -- provide default login redirect route name
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.admin.views.decorators import user_passes_test
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets

from . import bank_views, blood_views, user_views, views
from .models import BloodlineUser, BloodlineBank, BloodlineBlood

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'

# Serializers define the API representation for User.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BloodlineUser
        fields = ('id', 'username', 'first_name', 'last_name', 'gender', 'blood_type')

# Serializers define the API representation for Blood Bank.
class BankSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BloodlineBank
        fields = ('id', 'name', 'address', 'postcode', 'phone', 'email')

# Serializers define the API representation for Blood Donation.
class BloodSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BloodlineBlood
        fields = ('id', 'user', 'bank', 'donation_choice', 'donor_date', 'blood_status')

# ViewSets define the view behavior for BloodlineUser object.
class UserViewSet(viewsets.ModelViewSet):
    queryset = BloodlineUser.objects.all()
    serializer_class = UserSerializer

# ViewSets define the view behavior for BloodlineBank object.
class BankViewSet(viewsets.ModelViewSet):
    queryset = BloodlineBank.objects.all()
    serializer_class = BankSerializer

# ViewSets define the view behavior for BloodlineBlood object.
class BloodViewSet(viewsets.ModelViewSet):
    queryset = BloodlineBlood.objects.all()
    serializer_class = BloodSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

# Register ViewSets classes to urls type
router.register(r'users', UserViewSet)
router.register(r'banks', BankViewSet)
router.register(r'bloods', BloodViewSet)

# Provide the classname for the project
app_name = 'bloodline'
urlpatterns = [

	# Below are administrator/staff url related to user management
    url(r'^staff/users/(?P<pk>\d+)/user_update/$',
        user_passes_test(lambda u: u.is_staff)(user_views.UpdateUser.as_view()), name='user_update'),
    url(r'^staff/users/(?P<pk>\d+)/user_delete/$',
        user_passes_test(lambda u: u.is_staff)(user_views.DeleteUser.as_view()), name='user_delete'),
    url(r'^staff/users/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_staff)(user_views.DetailUser.as_view()),
        name='user_detail'),
    url(r'^staff/users/user_create/$', user_passes_test(lambda u: u.is_staff)(user_views.CreateUser.as_view()),
        name='user_create'),
    url(r'^staff/users/$', user_passes_test(lambda u: u.is_staff)(user_views.UserListView.as_view()), name='user_list'),

	# Below are administrator/staff url related to blood bank management
    url(r'^staff/banks/(?P<pk>\d+)/bank_update/$',
        user_passes_test(lambda u: u.is_staff)(bank_views.UpdateBank.as_view()), name='bank_update'),
    url(r'^staff/banks/(?P<pk>\d+)/bank_delete/$',
        user_passes_test(lambda u: u.is_staff)(bank_views.DeleteBank.as_view()), name='bank_delete'),
    url(r'^staff/banks/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_staff)(bank_views.DetailBank.as_view()),
        name='bank_detail'),
    url(r'^staff/banks/bank_create/$', user_passes_test(lambda u: u.is_staff)(bank_views.CreateBank.as_view()),
        name='bank_create'),
    url(r'^staff/banks/$', user_passes_test(lambda u: u.is_staff)(bank_views.BankListView.as_view()), name='bank_list'),

	# Below are administrator/staff url related to blood donation management
    url(r'^staff/bloods/(?P<pk>\d+)/blood_update/$',
        user_passes_test(lambda u: u.is_staff)(blood_views.UpdateBlood.as_view()), name='blood_update'),
    url(r'^staff/bloods/(?P<pk>\d+)/blood_delete/$',
        user_passes_test(lambda u: u.is_staff)(blood_views.DeleteBlood.as_view()), name='blood_delete'),
    url(r'^staff/bloods/(?P<pk>\d+)/$', user_passes_test(lambda u: u.is_staff)(blood_views.DetailBlood.as_view()),
        name='blood_detail'),
    url(r'^staff/bloods/blood_create/$', user_passes_test(lambda u: u.is_staff)(blood_views.CreateBlood.as_view()),
        name='blood_create'),
    url(r'^staff/bloods/$', user_passes_test(lambda u: u.is_staff)(blood_views.BloodListView.as_view()),
        name='blood_list'),

	# Below are client basic authentication and activation url
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'bloodline_app:login'}, name='logout'),
    url(r'^login/$', auth_views.login, {'template_name': 'bloodline/registration/login.html'}, name='login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
        name='activate'),

    # These url provide access for AJAX to interract with the Django classes
    url(r'^list_centre$', views.list_centre, name='list_centre'),
    url(r'^list_blood$', views.list_blood, name='list_blood'),

    # This url point to the client side appointment booking
    url(r'^appointment/$', user_passes_test(lambda u: u.is_staff) (blood_views.CreateBloodPublic.as_view()), name='appointment'),

    # Urls below related to password reset function
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {'post_reset_redirect': '/bloodline/reset/done/'}, name='password_reset_confirm'),
    url(r'^password_reset/$', auth_views.password_reset, {'post_reset_redirect': '/bloodline/password_reset/done/', 'email_template_name': 'bloodline/registration/password_reset_email.html'}, name='password_reset'),

    # Urls below direct to admin/staff page (requires staff level user)
    url(r'^staff/', views.staff_main, name='staff_main'),
    url(r'^admin/', admin.site.urls),

    # Url for RESTful API
    url(r'^api/', include(router.urls)),

    # Url for html header file
    url(r'^header/', views.header),

    # Url AJAX search form
    url(r'^base-search/', views.base_search),

    # Url to direct to index/home
    url(r'^$', user_passes_test(lambda u: u.is_authenticated)(views.Home.as_view()), name='home'),
]

bloodline_prj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	# basic routing to default django admin page from root project, e.g: localhost:8000/admin/
    url(r'^admin/', admin.site.urls),

    # route to open bloodline app
    url(r'^bloodline/', include('bloodline.urls', namespace="bloodline_app")),

    # route to trigger google OAuth social authentication
    url(r'^api/v1/', include('social_django.urls', namespace="social")),
]

bloodline/views.py
"""views.py

This module handles most of common view or requests from client

Variables:
	User {models} -- This variable provided the user model from the database to be used for User activation
	blood_type_dict {dictionary} -- this dictionary is used fo dynamic blood type search with ajax
"""

import json

from django.contrib.admin.views.decorators import user_passes_test
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_text
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.decorators.csrf import csrf_exempt
from django.views import generic

from .models import BloodlineUser, BloodlineBank, BloodlineBlood, BLOOD_CHOICES
from .tokens import account_activation_token
from .forms import BloodlineUserForm

User = get_user_model()
blood_type_dict = dict(BLOOD_CHOICES)

# Main page of the staff/administrator control
@user_passes_test(lambda u: u.is_staff)
def staff_main(request):
    return render(request, 'bloodline/staff_main.html')

# Page to provide user registration
def signup(request):
    if request.method == 'POST':
        form = BloodlineUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            # Set/make sure the user activation to false to provide email confirmation to verify it later
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('bloodline/registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

            # get raw password from user input, first row of the password field
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            mail_subject = 'Activate your BloodLine account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        # Assign provided user form for user registration on the presentation layer
        form = BloodlineUserForm()
    return render(request, 'bloodline/registration/signup.html', {'form': form})

# Class of index/main/home page
class Home(generic.ListView):
	# Uses the html template to contain the data required
    template_name = 'bloodline/home.html'

    # Give a 'tag' for dataset to be provided to the presentation layer
    context_object_name = 'donor_list'

    def get_queryset(self):
        # If user is aunthenticated, show the 10 recent donation that they making/made
        if self.request.user.is_authenticated():
            return BloodlineBlood.objects.filter(user=self.request.user).order_by('-donor_date')[:10]

# Used as the header of most pages for BloodLine
def header(request):
    return render(request, 'bloodline/header.html')

# Used as the 'form' for ajax search UI
def base_search(request):
    return render(request, 'bloodline/base_search.html')

# Used to let user to plan the blood donation or the staff
def appointment(request):
    return render(request, 'bloodline/appointment_request.html')

# Provide the service for user email confirmation function8
def activate(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
    try:
        # Get the text version or safe url in base64 form
        uid = force_text(urlsafe_base64_decode(uidb64))

        # Get user object based on the user that just registered
        user = User.objects.get(pk=uid)

    # If there's TypeError, ValueError, OverflowError, or user is not exist, set the user to 'none' or 'nothing'
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    # If user and account activation token is valid then set the user as 'confirmed' then log user in
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        # If user is none or account activation token is invalied then return 'Activation link is invalid!'
        return HttpResponse('Activation link is invalid!')

# AJAX function to search blood bank centre by address and postcode
@csrf_exempt
def list_centre(request):
	# Get the key_words from ajax
    key_words = request.POST.get('key_words')
    rejson = []

    # Select blood bank object based on postcode or address containing the key_words
    recontents_postcode = BloodlineBank.objects.filter(postcode__icontains=key_words)
    recontents_address = BloodlineBank.objects.filter(address__icontains=key_words)

    # Appending selected data into rejson list
    for recontent_postcode in recontents_postcode:

        # Put in blood bank name, address, postcode, phone and email into the list to return to user
        rejson.append(
            "BLOOD BANK CENTER: " + str(recontent_postcode.name) + " | " + str(recontent_postcode.address) + ", " + str(
                recontent_postcode.postcode) + " | " + str(recontent_postcode.phone) + " | " + str(
                recontent_postcode.email))
    for recontent_address in recontents_address:
        rejson.append(
            "BLOOD BANK CENTER: " + str(recontent_address.name) + " | " + str(recontent_address.address) + ", " + str(
                recontent_address.postcode) + " | " + str(recontent_address.phone) + " | " + str(
                recontent_address.email))

    # Sort the data inside rejson list
    rejson.sort()

    # Make the list 'unique', throw away the duplicates
    rejson = list(set(rejson))

    # Return the rejson data into the UI via AJAX
    return HttpResponse(json.dumps(rejson), content_type='application/json')

# AJAX function to search public profile that has specific blood type
@csrf_exempt
def list_blood(request):
	# Get the key_words from ajax
    key_words = request.POST.get('key_words')
    rejson = []

    # set the current type to keep track of which blood type that user are looking for
    current_type = 0

    # For every item in blood type list, if there's containg what's in the key_words, then put the 'code' into the current_type
    for each_type in blood_type_dict:
        if key_words.lower() in blood_type_dict[each_type].lower():
            current_type = each_type

    # If current type doesn't change, that means the blood type that user are searching for is not available on public
    if current_type == 0:
        return HttpResponse(json.dumps([]), content_type='application/json')

    # Select user object based on what blood type code that's being searched
    recontents = BloodlineUser.objects.filter(blood_type=current_type, public_profile=True)
    for recontent in recontents:

        # Put in user's username, blood type, address, mobile, and email into the list to return to user
        rejson.append("USER: " + str(recontent.username) + " | " + str(recontent.get_blood_type()) + " | " + str(
            recontent.address) + " | " + str(recontent.mobile) + " | " + str(recontent.email))

    # Sort the data inside rejson list
    rejson.sort()

    # Make the list 'unique', throw away the duplicates
    rejson = list(set(rejson))

    # Return the rejson data into the UI via AJAX
    return HttpResponse(json.dumps(rejson), content_type='application/json')

bloodline/templates/bloodline/blood_template/blood_create.html
{% extends 'bloodline/base_template.html' %}

{% block content %}

    {{ form.media }}
    <br><br><br>
    <div class="container" id="template-box">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div id="branding">
                    <h1>Create Blood Donation</h1>
                </div>
                <form method="POST" class="post-form" id="create-form">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td><input onclick="location.href='{% url 'bloodline_app:blood_list' %}';" type="button"
                                       value="Back"/> <input type="submit" value="Save"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

bloodline/templates/bloodline/blood_template/blood_delete.html
{% extends 'bloodline/base_template.html' %}

{% block content %}

    {{ form.media }}
    <br><br><br><br><br><br><br><br>
    <div class="container" id="template-box">
        <div class="row">
            <div class="col-md-2 col-md-offset-5">
                <div id="branding">
                    <h1>Delete Blood</h1>
                </div>
                <form method="POST" class="post-form">{% csrf_token %}
                <table>
                    <tr>
                        <td><p>Are you sure you want to delete "{{ object }}"?</p></td>
                    </tr>
                    <tr>
                        <td><input
                                onclick="location.href='{% url 'bloodline_app:blood_detail' pk=bloodlineblood.pk %}';"
                                type="button" value="Back"/> <input type="submit" value="Confirm"/></td>
                    </tr>
                </table>
            </form>
            </div>
        </div>
    </div>

{% endblock %}

bloodline/templates/bloodline/blood_template/blood_detail.html
{% extends 'bloodline/base_template.html' %}

{% block content %}

    {{ form.media }}
    <br><br><br>
    <div class="container" id="template-box">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div id="branding">
                    <h1>Blood Details • {{ bloodlineblood.user }}</h1>
                </div>
                <table>
                    <thead>
                    <tr>
                        <th>Info</th>
                        <th>Value</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>User</td>
                        <td><b>{{ bloodlineblood.user }}</b></td>
                    </tr>
                    <tr>
                        <td>Bank</td>
                        <td><b>{{ bloodlineblood.bank }}</b></td>
                    </tr>
                    <tr>
                        <td>Donor Date</td>
                        <td><b>{{ bloodlineblood.donor_date }}</b></td>
                    </tr>
                    <tr>
                        <td>Blood Status</td>
                        <td><b>{{ bloodlineblood.get_blood_status }}</b></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input
                                onclick="location.href='{% url 'bloodline_app:blood_update' pk=bloodlineblood.pk %}';"
                                type="button" value="Update Blood"/></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input
                                onclick="location.href='{% url 'bloodline_app:blood_delete' pk=bloodlineblood.pk %}';"
                                type="button" value="Delete Blood"/></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input onclick="location.href='{% url 'bloodline_app:blood_list' %}';" type="button"
                                   value="Back"/></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

bloodline/templates/bloodline/blood_template/blood_list.html
{% extends 'bloodline/base_template.html' %}

{% block content %}

    {{ form.media }}
    <br><br><br>
    <div class="container" id="template-box">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div id="branding">
                    <h1>Blood List</h1>
                </div>
                {% if blood_list %}
			<table>
				<thead>
					<tr>
						<th>No.</th>
						<th>User</th>
						<th>Bank</th>
						<th>Donor Date</th>
						<th>Donor Status</th>
					</tr>
				</thead>
				<tbody>
					{% for blood in blood_list %}
					<tr>
						<td>{{ blood.id }}</td>
						<td><a href="{% url 'bloodline_app:blood_detail' blood.id %}">{{ blood.user.username }}</a></td>
						<td><a href="{% url 'bloodline_app:blood_detail' blood.id %}">{{ blood.bank.name }}</a></td>
						<td><a href="{% url 'bloodline_app:blood_detail' blood.id %}">{{ blood.donor_date }}</a></td>
						<td><a href="{% url 'bloodline_app:blood_detail' blood.id %}">{{ blood.get_blood_status }}</a></td>
					</tr>
					{% endfor %}
					<tr>
						<td></td>
                		<td><input onclick="location.href='{% url 'bloodline_app:blood_create' %}';" type="button" value="Create Blood Donation" /></td>
            		</tr>
            		<tr>
						<td></td>
                		<td><input onclick="location.href='{% url 'bloodline_app:staff_main' %}';" type="button" value="Back" /></td>
            		</tr>
				</tbody>
			</table>
		{% else %}
		    <p>No blood registered.</p>
		    <input onclick="location.href='{% url 'bloodline_app:blood_create' %}';" type="button" value="Create Blood Donation" />
		    <input onclick="location.href='{% url 'bloodline_app:staff_main' %}';" type="button" value="Back" />
		{% endif %}
            </div>
        </div>
    </div>

{% endblock %}

bloodline/templates/bloodline/blood_template/blood_update.html
{% extends 'bloodline/base_template.html' %}

{% block content %}

    {{ form.media }}
    <br><br><br><br>
    <div class="container" id="template-box">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div id="branding">
                    <h1>Update Blood Donation Page</h1>
                </div>
                <form method="POST" class="post-form">{% csrf_token %}
                    <table>
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td><input
                                    onclick="location.href='{% url 'bloodline_app:blood_detail' pk=bloodlineblood.pk %}';"
                                    type="button" value="Back"/> <input type="submit" value="Update"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>

{% endblock %}